spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化大小
    initial-size: 8
    #连接池最小值
    min-idle: 8
    #连接池最大值
    max-active: 12
    #配置获取连接等待超时的时间(单位：毫秒)
    max-wait: 60000
  application:
    name: MovieTicketSpringBoot
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100
#  文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 电影封面上传路径（绝对路径）
movie:
  cover:
    upload:
#      path: /var/www/html/assets/movies/covers
      path: D:/Program/WebProgram/Vue/studentspace_browser/src/assets/Movies

mybatis:
  type-aliases-package: com.shaber.movieticket.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    plugins:
      - interceptor: com.github.pagehelper.PageInterceptor
        properties:
          helperDialect: mysql
          reasonable: true
          support-methods-arguments: true

logging:
  level:
    com:
      shaber:
        movieticket: DEBUG

server:
  port: 8090

snowflake:
  datacenter-id: 1    # 数据中心ID (0-31)
  machine-id: 1       # 机器ID (0-31)

pagehelper:
  helper-dialect: mysql       # 数据库类型
  reasonable: true            # 分页合理化
  support-methods-arguments: true

jwt:
  secret: 4E0eub2sXUg8Nep0Rszn0OodiQTZ/HVc6JbI4o4BHpCwE4nTGe/HLYyfCmlElUAsYiJQWAmerWljLTwErn6WbA==  # 替换为安全的密钥（建议加密存储）
  expiration: 3600                 # Token 过期时间（秒）

